---
- hosts: all
  become: true
  tasks:
    - name: Redémarrer les machines virtuelles
      shell: "shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: true
      become: true
      become_user: root

    - name: Attendre que les machines soient de nouveau accessibles
      wait_for_connection:
        timeout: 300
